services:
  node:
    image: hb9999/chatting-app:1.1
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3305
      - DB_USER=root
      - DB_PASSWORD=qhdnjs283
      - DB_NAME=chatting

  db:
    image: hb9999/mysql-chat:1.0
    environment:
      MYSQL_ROOT_PASSWORD: qhdnjs283
      MYSQL_DATABASE: chatting
    ports:
      - "3305:3305"
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data: